blog:
    image: metal3d/angular-yeoman
    volumes:
    - ./www/blog:/opt
    working_dir: /opt
    ports:
    - 9000:9000
    - 35729:35729
    extends:
        file: wraper.yml
        service: wraper

db:
    image: metal3d/json-server
    extends:
        file: wraper.yml
        service: wraper
    volumes:
    - ./db:/opt/db
    working_dir: /opt/db
    command: blog.json
    ports:
    - 3000:3000
